language: node_js
node_js:
  - 0.10
  - 0.12
  - iojs
  - stable
env:
 - NODE_PATH=./lib

install:
  - npm install
  - "cd resolvers/webpack && npm install && cd ../.."

script:
  - "npm run-script ci-test"
  - "cd resolvers/webpack && npm test"

after_success:
  - npm run coveralls
